# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.IntegerField(primary_key=True, serialize=False)),
                ('thread_name', models.CharField(max_length=90)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Thread', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('thread_id', 'comment_id')]),
        ),
    ]
