# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20200529_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
